name: surf_flutter_summer_school_24
description: "Surf Flutter Summer School '24"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  flutter_blurhash: ^0.8.2
  shimmer_animation: ^2.1.0+1
  cached_network_image: ^3.3.1
  
  dio: ^5.4.0
  retrofit: ^4.0.3
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  image_picker: ^1.1.2
  http: ^1.2.2
  provider: ^6.1.2
  nested: ^1.0.0
  shared_preferences: ^2.2.3
  auto_route: ^8.1.4
  elementary_helper: ^1.0.1
  elementary: ^3.0.0
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  intl: ^0.19.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  auto_route_generator: ^8.1.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
